version: '3.8'
services:
  mongo:
    image: mongo
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/hackathon
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - .env